### ISSUE TITLE
question: possible to take multiple photos without leaving camera screen?

### ISSUE THREAD

**Issue by jamesdixon** [Lightsnap/flutter_better_camera#1]
Hi there,

I was wondering if it's possible to take multiple photos without actually leaving the camera screen?

I'm working on an app where the user may want to take multiple photos at once (similar to iOS burst mode).

Thanks!

**Comment by ro0t** [comment]
Hi @jamesdixon I believe that's more of a client-side issue rather than something we can do in the camera plugin, an example app using this plugin is Lightsnap - disposable camera. In Lightsnap the user stays on the camera screen after taking a photo.

So you would probably need to implement that in your Flutter app logic

**Comment by gummie4444** [comment]
Your talking about enabling the Burst mode on the native cameras, this is not supported but should definitely be added.

We are gonna start working on this library in the next few weeks and I'll add this as a TODO

**Comment by jamesdixon** [comment]
@gummie4444 thanks for the quick reply! And yes, that's essentially what I'm trying to achieve. It's a bummer that iOS only allows us access to the stripped-down camera interface.

**Comment by gummie4444** [comment]
I'm pretty sure the iOS api allows you to do this, it's just a matter of writing the support with this Flutter plugin!

**Comment by gummie4444** [comment]
#12
